name: Build & Publish

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  pack-publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/PricingIntelligencePlatform.sln

      - name: Build
        run: dotnet build src/PricingIntelligencePlatform.sln --configuration Release --no-restore

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          $version = "${{ github.ref_name }}" -replace '^v', ''
          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV

      - name: Pack
        run: >
          dotnet pack
          src/PricingIntelligencePlatform.Sdk/PricingIntelligencePlatform.Sdk.csproj
          --configuration Release
          --no-build
          --output ./nupkg
          /p:PackageVersion=${{ startsWith(github.ref, 'refs/tags/v') && env.PACKAGE_VERSION || '1.0.0-preview' }}

      - name: Publish to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
